let peso = parseFloat(prompt("Informe seu peso?"))
let altura = parseFloat(prompt("Informe sua altura?"))
let imc = peso/(altura*altura)
alert(`imc ${imc.toFixed(2)}.`)
if (imc<18.5)
    alert("Abaixo do peso.")
else if (imc>=18.5 && imc<=24.9)
    alert("Peso normal.")
else if (imc>=25 && imc<=29.9)
    alert("Sobrepeso.")
else if (imc>=30 && imc<=34.9)
    alert("Obesidade Grau I.")
else if (imc>=35 & imc<=39.9)
    alert("Obesidade Grau II.")
else 
alert("Obesidade Grau III")